import assert from "node:assert/strict";
import fs from "node:fs";
const source = fs.readFileSync(new URL("../static/app.js", import.meta.url), "utf8");
const block = source.match(/async function inferAssistantIntent\(message\) \{[\s\S]*?\n\}\n/)[0];
const state = {assistantNextIntent:null, slug:"example",assistantHistory:[{role:"user",content:"Earlier correction"}],assistantRefs:[],bundle:{transcript_revision:"v1"}};
let seen;
const api = async (path, options) => {seen={path,body:JSON.parse(options.body)}; return {ok:true,json:async()=>({intent:"edit",replacement:{old:"Alpha",new:"Beta"}})};};
const fn = new Function("state","api","assistantError", `${block}; return inferAssistantIntent;`)(state,api,String);
const plan = await fn("Alpha，改成 Beta");
assert.equal(plan.intent,"edit");
assert.match(seen.path,/assistant\/intent$/);
assert.equal(seen.body.history[0].content,"Earlier correction");
state.assistantNextIntent="restructure";
assert.equal((await fn("按人物整理")).intent,"restructure");
assert.ok(!source.includes("restructurePatterns"));
const send = source.slice(source.indexOf("async function sendAssistant()"), source.indexOf("async function applyAssistantEdit("));
assert.ok(!send.includes("/apply"), "Sending a request must only preview, never apply");
console.log("Assistant intent: model routing, history and explicit controls passed");
