#!/usr/bin/env python3
"""Generate deterministic lightweight dependency locks with pip-tools."""

from __future__ import annotations

import argparse
import difflib
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PIP_TOOLS_VERSION = "7.6.1"
LOCKS = {
    "runtime": None,
    "ci": "ci",
}


def header(name: str, extra: str | None) -> str:
    extra_arg = f" --extra {extra}" if extra else ""
    return (
        "# This file is autogenerated; do not edit manually.\n"
        "# Python: 3.11\n"
        f"# Generator: pip-tools=={PIP_TOOLS_VERSION}\n"
        "# Command: python -m piptools compile pyproject.toml"
        f"{extra_arg} --output-file requirements/{name}.lock"
        " --no-header --no-emit-index-url --no-emit-trusted-host"
        " --resolver backtracking --strip-extras --quiet\n"
        "# Regenerate with: make lock\n"
        "\n"
    )


def compile_one(name: str, extra: str | None, output: Path, *, upgrade: bool = False) -> str:
    # pip-compile 复用 output 中仍符合依赖约束的 pins。每次在空临时文件中
    # 求解会追逐最新版本，让毫无依赖改动的 PR 因上游发布而随机变红。
    existing = ROOT / "requirements" / f"{name}.lock"
    if existing.is_file():
        output.write_text(existing.read_text(encoding="utf-8"), encoding="utf-8")
    command = [
        sys.executable, "-m", "piptools", "compile", "pyproject.toml",
        "--output-file", str(output), "--no-header", "--no-emit-index-url",
        "--no-emit-trusted-host", "--resolver", "backtracking", "--strip-extras",
        "--quiet",
    ]
    if extra:
        command.extend(["--extra", extra])
    if upgrade:
        command.append("--upgrade")
    subprocess.run(command, cwd=ROOT, check=True)
    return header(name, extra) + output.read_text(encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="compare regenerated locks")
    parser.add_argument("--upgrade", action="store_true", help="explicitly refresh dependency pins")
    args = parser.parse_args()
    if args.check and args.upgrade:
        parser.error("--check and --upgrade cannot be combined")
    if sys.version_info[:2] != (3, 11):
        raise SystemExit("dependency locks must be generated with Python 3.11")

    failures: list[str] = []
    with tempfile.TemporaryDirectory(prefix="meeting-locks-") as temp:
        temp_root = Path(temp)
        for name, extra in LOCKS.items():
            generated = compile_one(name, extra, temp_root / f"{name}.txt", upgrade=args.upgrade)
            destination = ROOT / "requirements" / f"{name}.lock"
            if args.check:
                current = destination.read_text(encoding="utf-8")
                if current != generated:
                    failures.extend(difflib.unified_diff(
                        current.splitlines(), generated.splitlines(),
                        fromfile=str(destination), tofile=f"generated/{name}.lock",
                        lineterm="",
                    ))
            else:
                destination.parent.mkdir(parents=True, exist_ok=True)
                destination.write_text(generated, encoding="utf-8")
    if failures:
        print("\n".join(failures))
        return 1
    print("dependency locks are reproducible" if args.check else "dependency locks updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
